name: ReviewAPP
on: 
    pull_request


jobs:
    validation:
        name: validate cloudformation template
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Check S3 buckets
              run: aws s3 ls
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
                AWS_DEFAULT_REGION: 'us-east-1'